# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
if [[ "$BASH_PROCESSED" == "BASH_PROCESSED" ]]; then
    return
fi

# Prevent recursion
BASH_PROCESSED="BASH_PROCESSED"

if [[ -f ~/.profile ]]; then
    source ~/.profile
fi

# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=-1

# Don't put my vpn or Yubikey commands in history
HISTIGNORE='vpn *:*eifjcc*:*eccccc*:rm -rf *'

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# Append to the history every time you enter a new command.
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Local configuration definition
# This should be for a machine specific configuration
# such are specific work configs
if [[ -f ~/.bashrc_local ]]; then
    . ~/.bashrc_local
fi

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [[ -f ~/.bash_aliases ]]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
    if [[ -f /usr/share/bash-completion/bash_completion ]]; then
        . /usr/share/bash-completion/bash_completion
        elif [[ -f /etc/bash_completion ]]; then
        . /etc/bash_completion
    fi
fi

if [[ -f ~/.powerlinerc ]]; then
    source ~/.powerlinerc
fi

if [[ -f ~/.cargo/env ]]; then
    source ~/.cargo/env
fi

export BASH_SILENCE_DEPRECATION_WARNING=1
